### ISSUE TITLE
Missing data files.

### ISSUE THREAD

**Issue by lemmih** [catherinetaylor2/Shape_Interpolation#1]
Hi, do you happen to still have 'dino2.obj' and 'dino3.obj'? Or perhaps different files containing meshes in the right format?

**Comment by catherinetaylor2** [comment]
Here are the files, I used. They were very roughly created in Maya so not the best meshes but can be used to demonstrate the code!

[dino_meshes.zip](https://github.com/catherinetaylor2/Shape_Interpolation/files/4751580/dino_meshes.zip)

**Comment by lemmih** [comment]
Thanks. Nice work, btw. I hope you got a good grade.
